### ISSUE TITLE
Server status indicator doesnt change if server is offline

### ISSUE THREAD

**Issue by dukesx** [Grief-Code/IPS-Server-Console#1]
The block i use shows server with a green indicator, but when the server goes offline, it still shows green, doesnt change to grey/etc to show its down

**Comment by Grief-Code** [comment]
@dukesx thanks for reporting the bug.
I've noted it yesterday already, I will fix it later today.

**Comment by dukesx** [comment]
@Grief-Code Okay sir! Good App Btw!
